# Github Overview {.unnumbered}

Github is a widely used tool for managing work and development on code-based projects. It has several key features:

1.  Version control - Github is based on **git**, a version control software. Git allows you to track changes in a project over time, and revert to previous versions if problems arise. You can also create **branches** of a project to work on new/experimental features without breaking the **main** code which might need to remain functional with no downtime. After completing the branch, the changes can be merged into the main code.

2.  Versatile - You can use Github to collaborate and track changes for any text- or script-based project. It is mostly used for hosting codes for web/software development or data analysis (SQL, SAS, R, Python), but you can also use it for complex [documentation on sourdough bread making](https://github.com/hendricius/the-sourdough-framework), [data storage for public use](https://github.com/sfu-db/covid19-datasets/tree/master), or [reports on cyber-security threats](https://github.com/jacobdjwilson/awesome-annual-security-reports).

3.  Web hosted - Github is a web application that can host public and private **repositories** (or **repos**). Anyone can see and download information on a public repo. Private repos can only be seen by individuals with approved access. For our purposes, [no sensitive code, PHI, passwords, tokens, or credentials can be stored in any repository, even if it is private.]{.underline} Github is great for working on projects for your own use, but it is also a fantastic way to share code with other users inside and outside TDH who might find it useful.

4.  Free - Anyone can create a free Github account. To interact with TDH repos, you should create your own account using your tn.gov email and two-factor authentication. We can then add you to any TDH CEDEP teams in Github, so you can start contributing.

## Organization

Our use of Github was only recently approved, so we are still working on the best way to integrate it into our teams. We have one main organization, TDH-CEDEP, with several program area subgroups (e.g., SSI, VH). Once you have your account, an admin can add you to the correct group(s). You will be able to view/download any public repository, but you can only see the private repositories for the teams you are a part of. You can also only make changes to repos for your teams.

If your program area does not have a team in TDH-CEDEP, let us know and we can create one easily. If you plan on having a lot of users and repos, it would be good to designate someone on your team to be an admin, so they can manage access permissions.

## Security

The following steps should be closely followed in order to adhere to our agreed upon security protocol with STS:

1.  Use your tn.gov email with two-factor authentication when setting up your Github account.

2.  Admins must promptly remove access permissions from users who leave CEDEP or transition between teams. They should also perform regular user audits.

3.  Only use Github for projects that need it. You can use Git locally, if you just need version control.

4.  Keep repositories private unless the project needs to be viewable by other jurisdictions and/or the public.

5.  Teams should develop and follow protocols to ensure that no sensitive data is published to any repos, public or private. See the security page for more details.
